// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __Model.Servicios = (function(_super) {

    __extends(Servicios, _super);

    function Servicios() {
      return Servicios.__super__.constructor.apply(this, arguments);
    }

    Servicios.fields("id", "providerproductactivityid", "descripcion", "numero_personas", "genero", "duracion_total", "orden");

    return Servicios;

  })(Monocle.Model);

}).call(this);
