// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.Servicios = (function(_super) {

    __extends(Servicios, _super);

    function Servicios() {
      return Servicios.__super__.constructor.apply(this, arguments);
    }

    Servicios.prototype.container = "table.results";

    Servicios.prototype.template = "<tr>\n              <td><b>{{id}}</b><br>\n              {{descripcion}} {{#estado}}<b>Ordenado</b>{{/estado}}\n              </td>\n        </tr>";

    return Servicios;

  })(Monocle.View);

}).call(this);
